### ISSUE TITLE
Consider updating libraries

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#121]
whilst checking matplotlib documentation, I realised, that we are using an "old" version (3.6.2 instead of 3.6.3). So I checked which libraries are up to date and found a few that had newer versions:

- matplotlib 3.6.2 -> 3.6.3
- scipy 1.9.3 -> 1.10.0
- setuptools 59.2.0 -> 67.2.0
- wheel 0.37.0 -> 0.38.4
- cython 0.29.32 -> 0.29.33
- numpy 1.23.3 -> 1.24.2
- pyparsing 3.0.7 -> 3.0.9
- pillow 9.3.0 -> 9.4.0
- packaging 21.3 -> 23.0
- contourpy 1.0.6 -> 1.0.7
- fonttools 4.31.2 -> 4.38.0

Is there any specific reason to have these versions besides just not having them updated in some time? If not, it might be worthto update these before the 1.5 release

**Comment by SjoerdB93** [comment]
The Flatpak Manifest for Matplotlib, scipy and numpy are build by hand. Meaning I set  the link to the PyPy wheels and the appropriate checksums myself. When creating these manifests these were the latest versions that were out and build successfully both for x86 and aarch.

All other dependencies are generated using flatpak-builder, which typically also just retrieves the latest versions using pip if I recall correctly.

If any library is not on the latest version, it's probably simply because I haven't updated them yet, often I just check the latest versions when updating runtimes but that's not because of any specific reason, generally I like to be on the latest releases. Thanks for the heads up, I'll give it a look tomorrow.
