### ISSUE TITLE
Consider Linting

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#135]
Out of sheer curiosity, I ran both flake8 and pylint against the existing codebase. A lot of things caught my attention there. 
Some things we already discussed (e. g. using `is None` instead of `== None`) showed up and a lot of other idiomatic decisions, for which we should conform to the PEP. I'll try to improve the "quality" of the codebase in an upcoming pr, based on most suggestions.

Some of them are pretty straight-forward and easily implemented (e.g. fixing whitespaces, newlines, import orders, etc.) But for some we should, if we want to discuss what settings we want to choose (e.g. max length of a line) and what we want to actually check for.

I'd suggest using [this github action](https://github.com/marketplace/actions/run-flake8-with-reviewdog) in CI, starting with Release 1.5 to have automatic annotations directly when opening prs. We could even consider setting it to fail, if code standard might not be met.

Just for transparency Here are my runs of both linters:
https://pastebin.com/W7vD0kLa
https://pastebin.com/iUuMTrjQ

I'm open for suggestions and feedback, if we want to use linting as a whole and in the way I've proposed

**Comment by SjoerdB93** [comment]
Yeah in general I think this is a good idea. The very first code base comes from me starting this as a personal project to help me with my graphs in my PhD thesis. Then it became quite useable so I put it out online, and then it developed into what this is new. 

So when first writing this, I didn't really consider too many standards, apart just "intuitive taste" so to say. 
Also, my personal background is in physics, and I'm pretty much self-taught in coding so that does leave some bad habits at certain points. As far as I've understood, scientists are kinda notorious for poor coding practices. Having said that, I do care about code quality and sustainable development, meaning this kind of workflow is definitely something we should set up.

On a personal note. I'll be finishing with my PhD this June, and got accepted for a post-doc in scientific development. With that in mind, more standardized/professionalised workflows are a thing I want to get into anyway. Also apart Graphs. So it's a good thing you bring this up.

I'm not very familiar with linting, but these runs do sound useful to get the code up to a better general standard. I've actually never considered single quotes to be preferred in Python. In fact, I always thought that for strings specifically double quotes were the preferred. Looking at PEP guidelines, it seems there's no formal recommendation. Is there any reason why window.py gets so many errors about `Double quotes found but single quotes preferred`?

**Comment by cmkohnen** [comment]
> In fact, I always thought that for strings specifically double quotes were the preferred. Looking at PEP guidelines, it seems there's no formal recommendation.

Okay, the default setting in flake8 is single quotes, which seems to be used exclusively in https://peps.python.org/pep-0008/ . It is something very simple to change using a runtime/config flag. We should however use one consistently in contrast to it's mixed state at the moment. Then I'd suggest using double quotes as it would be in line with xml, docstrings and both our intuition.

> Is there any reason why window.py gets so many errors about `Double quotes found but single quotes preferred`?

Does it? They're only for other classes since window only got two string literals, which are using single quotes

One side note:
I respect the amazing work you have already put into this project, and do apologize, if I seem arrogant/overly suggestive in any way. Since I am mostly self-taught as well, I do still lack experience and do not produce "high quality" code. This being my first proper python project, doesn't help with that either.

**Comment by SjoerdB93** [comment]
> and do apologize, if I seem arrogant/overly suggestive in any way. 

Just to comment quickly on this. Nah, I really appreciate your work in this project and think it's very useful. Without your help, Graphs wouldn't be nearly at the place it is right now. I wouldn't have close to enough time to get this kinda output  alone that we've had over the past months or so.
