### ISSUE TITLE
UI: Avoid grid of buttons

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#14]
Currently the interface has a grid of relatively random buttons on the left, which is not a pattern that makes sense in software, since actions should always be contextual and ideally connected to the content they affect. I can't make recommendations for what to do with all of them since I don't really know the main use cases/workflows for the app, but some general guidance:
- Actions should only be visible if they actually work in the current state (e.g. most of the buttons make no sense until there's data)
- Global app actions (e.g. save data) can go in the headerbar or primary menu
- Actions specific to the left pane could maybe go in a toolbar on the bottom of the left pane
- Less important actions could go in a menu/popover
- For selection this should use the regular selection mode pattern (like e.g. in Contacts) https://developer.gnome.org/hig/patterns/containers/selection-mode.html

![image](https://user-images.githubusercontent.com/1908896/212445971-6b5d5252-55cf-4622-85ee-4d72641207d2.png)

**Comment by SjoerdB93** [comment]
Hey,

Thanks for opening this issue. I agree that the grid needs an UI update. Another major issue for me, is that the layout quickly starts looking like a 2000's karaoke machine if I would add more buttons. It's quite pragmatic, everything is available and it works quite well, but it doesn't exactly scream modern design and there's a risk of getting overwhelmed with too many choices presented. Especially if adding more.

I wanted to mention that I'd actually asked for advice in the Gnome Design Matrix channel, but I see you that you were the one who responded. So thanks for that. Unfortunately I've been quite occupied with other stuff last two weeks, but next weeks should be better. 

To reply a bit more in-depth. I think the save data button indeed should go somewhere in the header bar (so either the bar itself, or more likely in a menu. Perhaps the primary menu). I like the idea of splitting the header bar as we see in many GNOME applications with a side-bar

The biggest challenge is probably the fact that almost all actions on the left-bar are all operations that are performed on the data sets (exceptions being "Select All/Select None", "Select span", and "Save Data"), in other words they kinda act the same.. 
All actions are also performed on the selected data (except for "shift vertically", which is performed on all data). So there's no obvious hierarchy here. They all basically behave the same, and they're all relevant at the same moment (which is, after you have opened a data set). The only exception maybe is "Cut Data", which is only really relevant when you have selected a span. See video:
[Screencast from 2023-01-14 16-24-25.webm](https://user-images.githubusercontent.com/68477016/212479563-0e1f9b44-866f-4faa-930a-40b1f2d7cbf0.webm)


The design as is, is for a part inspired by tools like Inkscape and GIMP. Where there's a side-bar with buttons to perform operations. The difference is that I use labels instead of icons, as I feel like icons in general are more difficult to read.  

I could categorize the buttons as such:
**Unrelated to data-set:**
- Select all
- Select None
**Actions on selected data sets:**
- Cut span
- Normalize
- Center Data
- Smoothen
- Translate X/Y
- Multiply X/Y
- Get Derivative
- Get Integral
- Get FFT
- Get Inverse FTT
- Transform Data
**Actions on all data sets:**
- Shift vertically (the fact that this one behaves differently is probably a design flaw, I should rethink the behaviour of this button)
**Other:**
- Select Span (this is a toggle button, if it's on you can drag and select a span of data on the graph itself, I'm thinking of moving this to the toolbar below the graph. However it kinda belongs together with the "cut span" button, as that one will cut the data that is within the selected span)
- Save Data (saves all open data as .txt files)

This categorization does not give an obvious way to order everything. Maybe it's best to split the header bar, and give the left-hand side panel some sort of action menu. The FTT for example are probably a bit obscure for the vast majority of people, and don't need to be there so prominently. Also the weird status of "Shirt vertically" indicates that it probably needs to be moved somewhere. The translate/multiply items could still be there on front. 
As I said on the Matrix channel, I probably need to experiment a bit as well. Which I'll be looking at in the next major update. (In the meantime I'll mainly push bug-fixes as actual updates, while Graphs 1.4 could include an UI overhaul).

Anyway, those are my (incoherent) thoughts on this issue, which is basically that indeed I think the UI needs some work there. The grid doesn't really scream modern design (let alone GNOME HIG).

**Comment by SjoerdB93** [comment]
The grid of buttons is now gone. 
Separate UI issues or suggestions should probably be in a separate issue.

**Comment by bertob** [comment]
Thanks for explaining! I'll look over the new layout in detail and file followup issues, but this is definitely already a bit clearer to understand.

**Comment by bertob** [comment]
Ok so after looking over it a bit I'm still not totally sure I get it, so I'd keep the discussion here for now and open other issues for specific things once I do.

Am I right in saying that there are essentially two modes when it comes to the actions in the toolbox (except for shift vertically, which IMO should be redone if it's the only one):
- Applies to the entire timeline (if there's no manual selection)
- Applies to the manually selected area only

If so, I think it'd be helpful to make the distinction between those two modes super obvious, e.g. by having a big toggle at the top for it, and initiating a preset default manual selection if you enter manual selection mode (so there's never no selection in that mode). In "Manual Selection" mode dragging on the canvas could then always apply a new selection, so you don't need to activate a specific tool for it.

Also, while I think grouping the actions makes sense, I don't think forcing them into rows does, most of the labels are too explicit or duplicate the button label. I'd maybe try a grid of buttons with label + icon (more detail can go in the tooltip).

Here's a quick sketch of what I mean:

![image405](https://user-images.githubusercontent.com/1908896/215566761-29bf760f-6870-46ce-b58e-25645c559843.png)

**Comment by SjoerdB93** [comment]
Thanks a lot for the detailed look and the ideas, it is really appreciated! 

> Am I right in saying that there are essentially two modes when it comes to the actions in the toolbox (except for shift vertically, which IMO should be redone if it's the only one):

First about the "shift vertically" option. This is indeed the single one exception, and I think you are right that this should be redone. It's non-intuitive that all non-active datasets are "safe" and won't change, but this one action is not. That doesn't make a lot of sense. At the very least, it should only apply this on the selected graphs but it might need some more rethinking. I initially implemented this when Graphs was still in the stage where it was just a tool to make my life easier. I had a few cases were I had like five graphs that I wanted on top of eachother, and I was simply looking for a way to automate this. But I agree that the current implementation makes little sense in the grand design.

Now to these two modes. All actions right now (apart from "Shift vertically") are applied to all "selected" Graphs (and nothing else). The only one that is special is "Select" and "Cut". "Select" is not really an action, but is instead used to highlight part of the figure. And the "cut" function, then cuts/deletes the datapoints that are within the highlighted area. So I could argue that the only weird one out may be the "Select" button, as it's presented as an action while it really is not. The other actions all behave the same. But I'm not 100% sure where to put this "Select" function. I've been thinking of ways to couple it with the "Cut" button, but didn't come to anything satisfying.  Possibly, it could be one single button. Then if you press it, you go into this selection mode and you can highlight the selected area, and if you press it again it then cuts the highlighted area. But then we'd need a clear way to cancel this action as well.

Regarding the sketch/mockup with a grid of buttons in the row. That honestly feels like a great idea, and in the sketch at least it looks really cohesive and nice. I think it would be a definite improvement over the rows.

**Comment by bertob** [comment]
> But I'm not 100% sure where to put this "Select" function. I've been thinking of ways to couple it with the "Cut" button, but didn't come to anything satisfying. Possibly, it could be one single button. Then if you press it, you go into this selection mode and you can highlight the selected area, and if you press it again it then cuts the highlighted area. But then we'd need a clear way to cancel this action as well.

In the context of #49 I was thinking that maybe Select, Pan, and Zoom would make the most sense as a top-level grouping since they're all modes for what dragging on the canvas does?

> Regarding the sketch/mockup with a grid of buttons in the row. That honestly feels like a great idea, and in the sketch at least it looks really cohesive and nice. I think it would be a definite improvement over the rows.

I guess the tricky part will be finding icons for everything, feel free to file issues against https://gitlab.gnome.org/Teams/Design/icon-development-kit if you don't find anything fitting there.

**Comment by cmkohnen** [comment]
> Here's a quick sketch of what I mean:
> 
> ![image405](https://user-images.githubusercontent.com/1908896/215566761-29bf760f-6870-46ce-b58e-25645c559843.png)

Reopening this, as I'm trying to implement this suggestion

**Comment by SjoerdB93** [comment]
> Reopening this

Sure, this issue is closely related to PR #49, and discussion on this issue has continued after closing it as well. 
I mainly closed it as the grid of buttons described in the original issue was mostly gone in the latest release.

But given the broader discussion and it's relevance to the still open PR I'm okay with keeping it open.
