### ISSUE TITLE
Remove select items menu

### ISSUE THREAD

**Issue by mossymossmoss** [SjoerdB93/Graphs#34]
The select items menu is fairly unintuitive, the options to unfocus or delete a graph could be placed alongside the change colour option. It may also be easier to understand if you make the change colour option a rectangle, as is often the case with other GNOME apps, as it is pictured here in a screenshot from Paper
![image](https://user-images.githubusercontent.com/56167669/215284011-3da0657e-344e-47e5-bc78-e2d6e4564a08.png)

**Comment by SjoerdB93** [comment]
It was actually suggested in the past to make the colour chooser circular, as it was a bit overbearing in a previous iteration. See attached picture for reference. 

![image](https://user-images.githubusercontent.com/68477016/215289580-9bb1953f-a91a-4b41-b55a-ec0d5bc5c465.png)

My intention was to make it so that if you double click on a data set, it would pop up the plot settings for this specific data set. Making it a lot easier to change things like the label, line styles, markers etc.. This worked well enough, but there's a nasty bug where the css of the item would get stuck in "selected" grayed mode for some reason so I didn't push that to production just yet. To have this behaviour, a separate selection mode would be needed.

In principle there's three actions that can be performed on an item. Change the colour, delete the item, and activate/deactive it. Having the selection and deletion behind a "selection" mode seemed like a logical way to achieve this while reducing the clutter. This is also consistent with design such as used in GNOME contacts:

[Screencast from 2023-01-28 21-39-38.webm](https://user-images.githubusercontent.com/68477016/215290180-d4c71828-e901-4402-87e7-c15cdae347b3.webm)

If you have specific improvements in mind to make the behaviour more intuitive I'm open to suggestions. But it was a concious decision to not add three different buttons to a single row. And the old behaviour of clicking anywhere on the row to select/deselect the dataset would conflict with the plan of opening the settings by double clicking on it.

**Comment by mossymossmoss** [comment]
The new setup is definitely an improvement, much more intuitive. I would like to still propose the idea of having the color selector be rectangular, as that would be in line with similar features in other apps and would further differentiate it from the graph selector

**Comment by SjoerdB93** [comment]
This is closely related to issue #54. The current GtkColorChooserWidget we use will be deprecated from Gtk 4.10 and on (which ships with GNOME 44), so we are gonna have to get rid of it. The alternative (GtkColorButton) is also deprecated, and they'll be replaced with GtkColorDialog from Gtk 4.10 and onwards (so not available yet).

I've been adviced on the GNOME matrix to use  GtkColorButton, as that one is closest to the GtkColorDialog which we're going to need to switch to anyway. Right now GtkColorButton however is hard-coded in style, and doesn't obey CSS. So we can't make it circular, instead you get a square widget. See the screenshot in issue #54.

With the above in mind, I am pretty open to using a square #54. I've got a branch in this repo where this widget is used instead (it's a bit out of sync with main, will fix that this weekend), but I haven't decided to merge it with main yet. Am also interested in the opinions of @cmkohnen here, or @bertob who suggested to use a circular (albeit smaller) widget in the first place. (Which I have to say, do like the look of).

The alternative by the way is to use a regular GtkButton, and make it trigger a modal ColorChooserDialog window upon click, and then just style that GtkButton. So it's not like it will be impossible to go for a circular button either as far as I know. Important for me personally is that we do try to follow GNOME design language, which perhaps does speak in favour of the square one but I haven't come across a lot of GNOME applications with a colour chooser to be honest.

**Comment by SjoerdB93** [comment]
Also, just to add. The current UI in the main branch is still a WIP, but I think it is getting clear which direction we're going. Overall I feel it's in a much better place than it was a week or two ago.

![image](https://user-images.githubusercontent.com/68477016/216779414-2be80446-e583-4da0-9d70-21aabfbe29eb.png)

**Comment by SjoerdB93** [comment]
Just as a reference, this is what it looks like if we'd move to GtKColorButton:

![image](https://user-images.githubusercontent.com/68477016/216788930-4fb991ac-a4f2-40d7-a49d-0957425134e0.png)

**Comment by mossymossmoss** [comment]
Liking the look of that!
