### ISSUE TITLE
Make dark mode plot background default adwaita dark background color

### ISSUE THREAD

**Issue by mossymossmoss** [SjoerdB93/Graphs#35]
It would look much nicer to have the background of the plot the same as the background of the window by default
![image](https://user-images.githubusercontent.com/56167669/215284085-a922bafd-7974-46b3-8aa0-e86d4555bb83.png)

**Comment by SjoerdB93** [comment]
The current background chosen is from the Matplotlib styles that are available by default in the matplotlib module, which drives all the graphing functionality in Graphs. It is possible to define own styles, so it's certainly possible to make it blend in with the background colour.

Having a purely white background is the general standard for presentations and publishing, and purely black would be the logical anologue for dark mode. I also do personally prefer a purely white background in light mode in looks, it blends in nicely with the white colours of the rows on the side-panel.

Having said that, I agree that the purely black looks a bit off in dark mode. Perhaps, to keep consistency with the light mode, it would make sense to use the same colours as the action rows again. Then it would look kinda like this:

![image](https://user-images.githubusercontent.com/68477016/215289310-6cb834f5-2fd5-44d3-9919-dab5e33b0ee5.png)

Purely black would then be offered as a seperate stylesheet.

**Comment by SjoerdB93** [comment]
For reference, here's with the black background, and again with the same background as the rest of the application. These are quick mock-ups I made in GIMP, but it's pretty achievable to implement:

![image](https://user-images.githubusercontent.com/68477016/215289343-019c67ec-10a7-4115-983c-c1a453421f6f.png)

![image](https://user-images.githubusercontent.com/68477016/215289353-7ee7d604-b6d2-489c-977e-5a7c8f6de3f4.png)

**Comment by cmkohnen** [comment]
To suggest something further:
Have styles, that fit GNOME as default and look visually appealing and when saving the data use a style that is suitable for publishing. This should allow for using the application in Dark Mode but exporting to a white style sheet.
This could be achieved either via popup window, or a preferences option.

**Comment by SjoerdB93** [comment]
Yes, I think that may be quite a good solution. The save button is by default coupled to the "Save" command that is build into the navigationbar, so it's a bit of a black box (I can make a custom function as well, but this one works quite well). This command uses the rcparams in matplotlib for the saving parameters, the ones related to saving figures are as follows:

```
## background white
#savefig.dpi:       figure      # figure dots per inch or 'figure'
#savefig.facecolor: auto        # figure face color when saving
#savefig.edgecolor: auto        # figure edge color when saving
#savefig.format:    png         # {png, ps, pdf, svg}
#savefig.bbox:      standard    # {tight, standard}
                                # 'tight' is incompatible with pipe-based animation
                                # backends (e.g. 'ffmpeg') but will work with those
                                # based on temporary files (e.g. 'ffmpeg_file')
#savefig.pad_inches:  0.1       # padding to be used, when bbox is set to 'tight'
#savefig.directory:   ~         # default directory in savefig dialog, gets updated after
                                # interactive saves, unless set to the empty string (i.e.
                                # the current directory); use '.' to start at the current
                                # directory but update after interactive saves
#savefig.transparent: False     # whether figures are saved with a transparent
                                # background by default
#savefig.orientation: portrait  # orientation of saved figure, for PostScript output only
```

Right now, I already have the `savefig.transparent` as optional option. Setting `savefig.faceolor` and `savefig.edgecolor` to a default value for any style sheet would be quite trivial. Then we can just an option in the preferences (or as a popup) whether it should use a default white stylesheet for saving, or just the stylesheet that's currently in use.  

The remaining question is what colours to use by default as stylesheet. As I agree that the pure black in dark mode isn't the most aesthetically pleasing. So that would be either the same colours as the ActionRows, or the same colour as the background probably. (See figures below). For the light variant, I feel like having a pure white background is fine, it does also match with the Adwaite ActionRows. But I'm open to feedback on that if there's strong feelings on that choice.

![image](https://user-images.githubusercontent.com/68477016/215289310-6cb834f5-2fd5-44d3-9919-dab5e33b0ee5.png)

![image](https://user-images.githubusercontent.com/68477016/215289353-7ee7d604-b6d2-489c-977e-5a7c8f6de3f4.png)
