### ISSUE TITLE
Automatically set axis labels when loading data from file

### ISSUE THREAD

**Issue by mossymossmoss** [SjoerdB93/Graphs#38]
When the following data is loaded, this is the plot which results
![image](https://user-images.githubusercontent.com/56167669/215284871-c80d77d7-abd3-400a-a0ac-b0c202d1c925.png)
![image](https://user-images.githubusercontent.com/56167669/215284835-c3c041a9-d0b4-4641-8aec-b8d19abe52a6.png)

The data has column labels on the first line, it would make sense if Graphs could detect this and set it's axis labels accordinly

**Comment by SjoerdB93** [comment]
Thanks for the suggestion. This is indeed a functionality that would be nice to have, and I would like to implement.

For specific cases it's quite easy to implement, but I need to think of some kind of heuristic to make it work in the vast majority of times. To split the data in columns for instance I just use regular expressions with the "/s+" as default value, so any repetitions of whitespaces is seen as a new column. From your example it can clearly be seen that this is not a good rule for headers, "Average Heigth" also has a whitespace for instance.

I could check for column positions, in this specific case the headers are neatly aligned with the data. But in my experience that's not always the case at all so I'm not sure if that's the good way to go. I could also try and detect what is used as separator for the data, and then just automatically apply this separator for the headers as well, but that would not work in this case either. The data is separated by fewer whitespaces than the headers. One option could be to just use "any amount of whitespaces that are more than one" . One option would also just to have a reasonable default value, and then just make it a setting that one can change if the default value doesn't work for them.

Either way, I will probably try and implement such a functionality. But I will have to think about how to implement it correctly so that it will be correct for most cases.
