### ISSUE TITLE
Update the appid?

### ISSUE THREAD

**Issue by cmkohnen** [SjoerdB93/Graphs#40]
The current appid still reads as se.sjoerd.DatMan, however all visual references, as well as Github and the linked website do name the application as Graphs.

Should this be updated?
The main implication, apart from changing all references in code and build configuration, would be flatpak. A new appid would need to be requested on flathub and all user configuration would be lost.

It would however be more intuitive for users as well as contributors and should, if chosen to, be done before the project enters a nautilus/files state, where changing it would be a to monumental task.

**Comment by SjoerdB93** [comment]
Yes, it would also be much nicer to find the application from the CLI. 
The appid that it has right now, was because the initial build was called DatMan, short for Data Manipulator. I agree that se.sjoerd.Graphs would make much more sense.

As far as I understood, to change the appid on Flathub, I need to submit the application again to Flathub as a PR. 
I don't think user configuration being lost is the end of the world. As it is right now, it resets user configuration also when the keys no longer match with the templates for instance (otherwise you run into key errors). 

I'm not sure if existing installs just "migrate" over to the new app id. I will probably also lose the statistics (Graphs is on 1731 total installs right now), but the latter is not that important. I'll ask around on the Flatpak matrix channel.

**Comment by SjoerdB93** [comment]
I'm still not sure if manual intervention is necessary for people who have installed the application, but this indeed needs to be done by just pushing a PR to Flathub with this request, similar to get an app published on Flathub in the first place:

From another issue:
> As mentioned before, just open a new merge request with the new app-id and one of the reviewers will merge it and end of life the old app-id. 

I think it would probably be nicest if we can rename it from se.sjoerd.DatMan to se.sjoerd.Graphs. So once we've got those changes prepared, I can go ahead and request the change on Flathub.

**Comment by SjoerdB93** [comment]
I have submitted [a PR to Flathub](https://github.com/flathub/flathub/pull/3865). It's combined with a very minor update towards v 1.4.1, as the latest Flatpak build needs to be done from the commit with the latest changes.

Will close this issue as soon as it's merged, in the unlikely event it gets denied I would switch back to the old app-id.

**Comment by SjoerdB93** [comment]
The flathub PR got merged, so I'm closing this issue. Our appid is now officially changed.

**Comment by SjoerdB93** [comment]
Just as an FYI, it seems both from the CLI as well as from GNOME Software, existing users automatically get migrated over to the new app-id. I was personally a bit worried they'd get stuck with a deprecated version and a warning in the CLI, and tat manual intervention was necessary. This is not the case. From the GUI it even happens quietly, without telling the user.

![image](https://user-images.githubusercontent.com/68477016/216571861-7a818982-d7ad-4f85-9602-e562ad5e76d7.png)

Also, the install statistics from Flathub beta is carried over, and we just passed 2000 total installs 🥳:
![image](https://user-images.githubusercontent.com/68477016/216571991-6aa83938-e768-4468-8640-1a436455b17a.png)

I'm pretty sure it counts someone updating the program as a new install, but that's still a nice milestone.
