### ISSUE TITLE
Plot Settings: Drop Apply

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#52]
Generally "Apply" buttons should only be used when there's no alternative (e.g. when the action can not be undone), otherwise options should just insta-apply.

**Comment by SjoerdB93** [comment]
When changing Data Set, it loads all settings for that new data set without saving the old one. This button was added because sometimes you want to set the settings for a certain data set (for example change the line style), and then go to the other one and change some settings there. 

While I'm typing this, I see the solution is simple. Just couple a save action to the trigger when a new data set is loaded. 
In reality, changes are not applied instantly. But they are applied when closing the "Plot Settings" menu, or when changing dataset, which is essentially "instantly" for all intents and purposes. That would make this button completely redundant as well. Will fix this.
