### ISSUE TITLE
Simplify equation list

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#54]
There are a few oddities with the equation list as-is, namely:
- [x] The selection mode and non-selection mode states are very similar (basically just replacing a check with an interactive check, and the color with the delete button), making the two modes feel unnecessary. I'd move the interactive check to the left and always have it visible, and have color chooser and delete always visible on the right.
- [ ] The list has card styling, but doesn't behave like a real card (e.g. it doesn't grow with the content). I'd drop the card styling and add a clear separator between the two scrolling areas or make the list height dynamic and make the entire sidebar a single scrollview.
- [ ] The color dot is too large, I'd make it about 20px

![image](https://user-images.githubusercontent.com/1908896/215569460-a0eb4c4c-e64a-46b6-a68f-b62c7e9f899e.png)

![image](https://user-images.githubusercontent.com/1908896/215568820-49cb7416-e5d0-48ff-92a4-515c5bb1a969.png)

**Comment by bertob** [comment]
Of the three points mentioned in the issue only the first was fixed by #49, so I'd keep this open or open separate issues for the other two things.

**Comment by bertob** [comment]
> I'm personally inclined to just make the entire sidebar a single scrollview, simply because I like the look of the cards. But it's something we should experiment with anyway.

+1 for a single scrollview, that's probably the simplest solution here.

**Comment by SjoerdB93** [comment]
> Of the three points mentioned in the issue only the first was fixed by #49, so I'd keep this open or open separate issues for the other two things.

Agreed, this was an oversight in merging the PR and opting for fixing the open issues in seperate PRs. This was still on the to-do list.

**Comment by cmkohnen** [comment]
Sorry for responding not at an earlier time.
I would keep the sidebar as two scroll wheels, or at least keep the option to enable it that way.
The reason being consistency. If handling multiple lines for the graph, thus making the list expand, would move the quick navigation buttons, and one would always have to search a (maybe very) short moment to find them. Quickly selecting lines for the different operations to perform would also prove difficult, as one would have to scroll up and down more often.
I would suggest, letting the user resize the item list by themselves, so if they wish to expand it they have the power to do sow and do it exactly how large they want.

**Comment by SjoerdB93** [comment]
I believe the issue raised is mainly that a static size is not how these cards generally behave and is therefore not consistent with typical GNOME design. So if we use this current styling, the cards should dynamically expand based on the amount of open data sets. Having the cards resizable by the user doesn't really change that.

What maybe could work is to have the cards expand on new data. But put this expanding area itself into a scrollable area, so that the card itself can be scrolled over this area and not to the rows inside of the card. Thus keeping the rest of the UI at it's current fixed position. So the biggest change would basically be style-wise, the whitespace below the open data rows would disappear. In that case maybe we should add a GTKSeperator just above the mode toggles to make a clear distinction between the data area and the user area.

Either way I'm inclined to agree that UI elements/buttons shouldn't be moving around, as that would just destroy any muscle memory a user world build up and therefore be annoying in workflow.

**Comment by bertob** [comment]
Yeah, I think the two possible directions here are
- Single scrollview with card style
- Two (potentially resizable) panels without card style

Regardless of which you go with it might be good to think about making the actions section more predictable. For example, if we could squeeze 2 entries per row in the second section maybe we could get rid of the expanders and just have groups with headers?

**Comment by SjoerdB93** [comment]
Regarding the style of the ExpanderRows (so the actions), is it against the typical GNOME design language to have these kind of rows in a card? As far as I understood, these cards being able to grow in size with expanding content is not really anything weird, it happens all the time in GNOME applications. See how the card expands in the amount of Bluetooth options for example:

![image](https://user-images.githubusercontent.com/68477016/216549398-d8af5b98-523e-46df-a89b-a32da976d481.png)

I was personally thinking of having something along these lines. Put the "equation list" (or more accurately perhaps, data list) as a whole in one single scrollview with a fixed size. But make the size of the GtkBoxList expand when adding new data. So this would get rid of the whitespace below the each data set, while keeping the rest of the sidebar at the same location. So this means that the card does grow with content, but it is put in a scroll window so as soon as the Card becomes too big to fit, then you can scroll the card up and down. Similar to how the Settings window itself doesn't expand when the amount of Bluetooth options become too large to fit the window, instead the panel becomes scrollable, see screencast below. (Just to clarify, the idea is to just make the top part scrollable in that case, so that all actions are always on the same position still).

[Screencast from 2023-02-03 09-28-40.webm](https://user-images.githubusercontent.com/68477016/216550318-cd7f8f37-83bb-4ad9-beb3-48bab58e0626.webm)

Would this be against any existing design language? Does anyone have other suggestions or opinions on this kind of behaviour? I'm personally kinda leaning towards these card views, again mostly because I really like the aesthetics. But we are trying to follow GNOME design language and the HIG, so if it clashes with that then that's a solid argument for me honestly. However, I kinda do have issues with both suggested directions here:

> Single scrollview with card style

My problem here is what @cmkohnen wrote. The problem with this is that all the GUI actions will be changing places depending on how much data is loaded. This takes away all potential muscle memory that one might grow with the applications, and you will keep looking for like 1 second to change into zoom mode. I feel this would simply disrupt workflow a bit too much. Also, and this is a niche case, currently it's possible to load let's say 100 data sets and perform the same action on all of them. So let's say you want to normalize all of your data quickly, you can do this really quickly and efficiently. However if the entire action menu moves down to load all the cards for each data set, you'll have to scroll way down just to change the zoom for instance. This does not feel like a great idea. An alternative would be to just put the modes (Pointer/Zoom/Pan/Select) outside of the scroll window, but the problem remains for the actions themselves.

> Two (potentially resizable) panels without card style

My main problem here is that it looks worse without solving anything in my view. I quickly changed the style of the data set GtkBoxList to a sidebar style. It's just the same but worse looking (in my opinion). 

![image](https://user-images.githubusercontent.com/68477016/216551510-d32c5bdd-fcbf-49a8-b2e9-acef8e1d9db9.png)

Also, I'd like to add that typically you're not going to load more than a hand full of data at the same time. But it is something that one might want to do if one is more interested in data manipulation than graphing (and again, my vision of the application is that it should do both), and I think it's a usecase that should be supported. 

I'd like to hear any opinions of this, to me this is really a bit of an open question.

**Comment by SjoerdB93** [comment]
> For example, if we could squeeze 2 entries per row in the second section maybe we could get rid of the expanders and just have groups with headers?

This could certainly a realistic thing to do, it already fits on a standard 1080p screen as-is, so if we squeeze the second section into two rows (like the original grid lay-out), it wouldn't be that long either, on smaller screens it could then be scrollable. But I can see potential issues if future functionality were to be added. Also it presents the user with a lot of options right out of the bat, making the menu maybe a bit more intimidating.

**Comment by cmkohnen** [comment]
Just a quick experiment:
![grafik](https://user-images.githubusercontent.com/59118042/216789633-81d12240-18a0-4f2a-a0e2-00e40344dcd8.png)

**Comment by SjoerdB93** [comment]
That's cool, is it fully functional?  Would be nice to compare this to a 20 px dot to see how that looks as well. So far I've only tried to reset the size of the circular GtkButton it is right now with a size-request but it takes that as a minimum size it seems, it still expands in size to fill the rows. But I haven't looked too deep into it yet.

**Comment by cmkohnen** [comment]
Yes and no, I've tried lots of things to try and shrink this button, with little to no gain, so I tried this.
Two caveats however: 
- minor: hovering over the button tints the whole button in the selected color
- major: somehow this **completely** breaks having multiple items and I couldn't figure out why
I'll open a pr with these changes in a moment

**Comment by SjoerdB93** [comment]
> major: somehow this completely breaks having multiple items and I couldn't figure out why
I'll open a pr with these changes in a moment

I found the issue, it had to do with the uuid that was generated for each data set not being unique for some reason. I changed it such that it generates this uuid in the __init__ function in the data class, and that solves the issue. The attributes that are generated in the @dataclass decorator before the __init__ functions are mostly meant as templates. My guess is that they don't actually get assigned a value before they're explicitly being declared in some function.
