### ISSUE TITLE
View menu papercuts

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#60]
Menu items that toggle something on/off should actually show the state in the menu with a checkmark

- [ ] The sidebar option should be "Show Sidebar" and have a checkmark
- [ ] The two logarithmic ones can keep the label if we make add checkmarks, or alternatively they could each have a title like "X Axis" and two options with radios ("Linear" and "Logarithmic") below

![image](https://user-images.githubusercontent.com/1908896/215915509-601724e4-3e7e-4989-bcca-caacabeb3f34.png) 

The view menu in Text Editor is a good example of a similar menu:

![image](https://user-images.githubusercontent.com/1908896/215915626-eab4ea15-36c8-4785-9407-179fcfedbb42.png)

**Comment by SjoerdB93** [comment]
Yes, most of this was actually on my list. Regarding the axes properties, I'm thinking of adding square root scaling as well in the future (although not in the 1.5 release, it's not as trivial as you'd suspect actually to add completely custom scalings, yet very doable just not my highest priority). So I'm kinda trying to see if I can find a solution that would allow for three options.

**Comment by cmkohnen** [comment]
I would suggest using the approach with a section, as this would allow for future implementation of different scaling options

**Comment by SjoerdB93** [comment]
Regarding the scaling, it should be noted that the scaling on the left-hand and the right-hand axis can be different. So it's possible that the left-hand axis is in linear scale, and the right-hand axis is in log scale. This is by design.

What the button does, is that it toggles this scaling for the selected data sets. So if the data set that is plotted with the y-axis on the left is active, but the data set that is plotted on the right-hand y-axis is not. Then it only toggles the left-hand axis, and vice versa. With that in mind, I think it should be something denoting "Toggle X-scale" or something in that vain.
