### ISSUE TITLE
Make primary toolbar buttons exclusive

### ISSUE THREAD

**Issue by bertob** [SjoerdB93/Graphs#62]
An important aspect of toolboxes in creative tools is that tools are modes, and that there's always exactly one of them that's active. This way it's always predictable what's going to happen when you click on the canvas. Currently this isn't the case, because
- Reset is not a mode, but just a singular action
- It's possible to have none of the modes be active

I'd make the tools exclusive buttons where one is always toggled, ideally using [this widget/pattern](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/212) but if that's too hard, a regular stack switcher would work for now.

**Comment by SjoerdB93** [comment]
There's basically two modes there then, zoom and pan. And then there's the reset action. Would you then suggest to have one switcher with "Neutral mode", "Zoom mode" and 'Panning mode", plus the regular reset button put there somewhere?

You could make the neutral mode to reset as well, but I'm not sure how intuitive that is to most people.

**Comment by SjoerdB93** [comment]
Just to add to this. The current implementation with just regular toggle buttons for zoom mode and pan mode is the standard design language in these kind of applications. In fact, some applications I've seen have even worse implementations for this where this needs to be triggered by a right-click menu, and then selecting a mode. (Which I'm not a fan of)

But I'll be honest. Most similar applications have a god-awful design. Even expensive proprietary graphing applications such as OriginLabs have a design that is straight from the early 2000's, and we've paid a $800 license fee to use it. See attached screenshot:

![image](https://user-images.githubusercontent.com/68477016/215993855-b6e3a4ed-3882-4b5c-a7e6-e8e308ee03d1.png)

 Which is no disrespect to the respective developers, but my theory is that it's a result of these applications being built by scientists and engineers who often have a more pragmatic approach to this. Also, in particular OriginLabs is very powerful and has a lot of features. It's inherently difficult to add so many features while keeping the design itself sane. This is also why my view with Graphs is not to make a competing product to these kind of tools, as they have their place, but have something more of a middle ground that fits with most use-cases. So I'm really not trying to talk down on these kind of applications. What I am just trying to say is that I'm happy with borrowing some of the design language from creative tools rather than engineering tools, as the latter are not really what I consider the design we should be aiming for.

**Comment by cmkohnen** [comment]
> There's basically two modes there then, zoom and pan. And then there's the reset action. Would you then suggest to have one switcher with "Neutral mode", "Zoom mode" and 'Panning mode", plus the regular reset button put there somewhere?

I actually implemented the select button the be a third mode, so it doesn't conflict with the two modes inherited by the toolbar.

**Comment by SjoerdB93** [comment]
> I actually implemented the select button the be a third mode, so it doesn't conflict with the two modes inherited by the toolbar.

This is a good point, and also relevant in the context of issue #61. If we move the Select and cut feature to the "Adjust Data" group, it would imply that we have a toggle of mode in within the action menu, which is very inconsistent. (Turning on selection mode _must_ turn off zoom or pan mode, having them all activated is mutually incompatible).

It is possible to just put selection mode up there, and move the "Cut data" action into "adjust", but I'm not really sold on the idea that that this an improvement. Such splitting would be make sense though if we would implement the idea that when a selected highlight is shown, that all actions are only applied upon this selected part, this is very possible to implement but the main question is if that is desired behaviour. (It could be interesting e.g. in niche cases where you only want to smooth part of the data I guess)

**Comment by cmkohnen** [comment]
I would only move the cut button into the adjust category, if we would make all other actions apply only to the selected span.
Regarding reset, I could see an option to remove it if we introduce keyboard shortcuts for reset, back and forward, which is no problem, as these are already coupled to actions anyway.
